# Лабораторне заняття №1

## 1 Перестановки

### 1.1 Використовуючи власну функцію

In [1]:
def permute(A):
    if len(A)==1:
        return [tuple(A)]
    permutations = []
    for x in A:
        for y in permute(A-{x}):
            permutations.append((x,)+y)
    return permutations

In [2]:
A = {1, 2, 3}

In [3]:
# Використовуючи власну функцію
permute_all = set(permute(A))
print("Перестановки множини {}: {}".format(A,permute_all))
print("Кількість перестановок: ", len(permute_all))

Перестановки множини {1, 2, 3}: {(3, 1, 2), (3, 2, 1), (2, 3, 1), (1, 2, 3), (1, 3, 2), (2, 1, 3)}
Кількість перестановок:  6


### 1.2 Використовуючи бібліотеку `itertools`

In [4]:
from itertools import permutations
import numpy as np

In [5]:
A = {1, 2, 3}

In [6]:
# Використовуючи бібліотеку itertools
permute_all = set(permutations(A))
print("Перестановки множини {}: {}".format(A,permute_all))
print("Кількість перестановок: ", len(permute_all))

Перестановки множини {1, 2, 3}: {(3, 1, 2), (3, 2, 1), (2, 3, 1), (1, 2, 3), (1, 3, 2), (2, 1, 3)}
Кількість перестановок:  6


### 1.3 Задача
Виведіть всі можливі перестановки та порахуйте їх кількість від таких множин:
- {1, 3, 5}
- {1, 2, 3, 4}
- {1, 2, 2, 1}

Порахуйте кількість перестановок таких множин:
- {1, 2, 3, 4, 5}
- {1, 2, 3, 4, 5, 6, 7}
- {1, 3, 5, 7, 9, 11, 13, 15, 17, 19}

**Зауваження.** Спробуйте задати множину $\{1, 2, 2, 1\}$ у вигляді списку, тобто $A = [1, 2, 2, 1]$.

In [7]:
# Місце для Вашого коду

A = {1, 3, 5}
permute_all = set(permutations(A))
print("Перестановки множини {}: {}".format(A,permute_all))

A = {1, 2, 3, 4}
permute_all = set(permutations(A))
print("Перестановки множини {}: {}".format(A,permute_all))

A = [1, 2, 2, 1]
permute_all = set(permutations(A))
print("Перестановки множини {}: {}".format(A,permute_all))

A = {1, 2, 2, 1}
permute_all = set(permutations(A))
print("Перестановки множини {}: {}".format(A,permute_all))

A = {1, 2, 3, 4, 5}
permute_all = set(permutations(A))
print("Кількість перестановок: ", len(permute_all))

A = {1, 2, 3, 4, 5, 6, 7}
permute_all = set(permutations(A))
print("Кількість перестановок: ", len(permute_all))

A = {1, 3, 5, 7, 9, 11, 13, 15, 17, 19}
permute_all = set(permutations(A))
print("Кількість перестановок: ", len(permute_all))


Перестановки множини {1, 3, 5}: {(1, 5, 3), (3, 5, 1), (5, 3, 1), (1, 3, 5), (3, 1, 5), (5, 1, 3)}
Перестановки множини {1, 2, 3, 4}: {(4, 3, 1, 2), (2, 3, 1, 4), (4, 1, 2, 3), (3, 4, 2, 1), (1, 2, 3, 4), (3, 4, 1, 2), (2, 1, 3, 4), (3, 2, 4, 1), (2, 3, 4, 1), (1, 3, 2, 4), (1, 4, 2, 3), (2, 4, 3, 1), (4, 2, 1, 3), (2, 4, 1, 3), (3, 1, 4, 2), (1, 2, 4, 3), (2, 1, 4, 3), (3, 1, 2, 4), (4, 1, 3, 2), (1, 3, 4, 2), (3, 2, 1, 4), (4, 2, 3, 1), (1, 4, 3, 2), (4, 3, 2, 1)}
Перестановки множини [1, 2, 2, 1]: {(1, 2, 1, 2), (1, 1, 2, 2), (2, 1, 1, 2), (2, 2, 1, 1), (2, 1, 2, 1), (1, 2, 2, 1)}
Перестановки множини {1, 2}: {(1, 2), (2, 1)}
Кількість перестановок:  120
Кількість перестановок:  5040
Кількість перестановок:  3628800


### 1.4 Задача
Виведіть всі можливі перестановки без нерухомих точок та порахуйте їх кількість від таких множин:
- {1, 2, 3}
- {1, 2, 3, 4}
- {1, 3, 5, 7}
- {1, 2, 2, 1}

_Перестановка без нерухомих точок_ - це така перестановка, в якій позиція кожного елементу не збігається з його позицією в початковій множині.
**Приклад.** Для множини {1, 2, 3, 4, 5}:
- {4, 1, 5, 2, 3} - перестановка без нерухомих точок
- {4, **2**, 1, 3, **5**} - перестановка з нерухомими точками

In [8]:
# Місце для Вашого коду
print("for {1, 2, 3} ")
a = np.array([1,2,3])
r = np.arange(1,4)
for i in permutations(a):
    if (i == r).sum() == 0:
        print(i)
        
print("for {1,2,3,4} ")
a = np.array([1,2,3,4])
r = np.arange(1,5)
for i in permutations(a):
    if (i == r).sum() == 0:
        print(i)

print("for {1,3,5,7} ")
a = np.array([1,3,5,7])
r = np.array([1,3,5,7])
for i in permutations(a):
    if (i == r).sum() == 0:
        print(i)
        
print("for {1, 2, 2, 1} ")
a = np.array([1, 2, 2, 1])
r = np.array([1, 2, 2, 1])
print(set(permutations(a)))
for i in permutations(a):
    if (i == r).sum() == 0:
        print(r)
        print(i)
#не зрозуміло, чому виводить 4 рази (2,1,1,2), оскільки в set(permutations(a)) воно міститься тільки один раз... і це, певно, не через те, що дві двійки і одинички мають  
#різну індексацію в r, оскільки, якщо проходити по циклу, то воно наткнеться тільки один раз на правильну відповідь.



for {1, 2, 3} 
(2, 3, 1)
(3, 1, 2)
for {1,2,3,4} 
(2, 1, 4, 3)
(2, 3, 4, 1)
(2, 4, 1, 3)
(3, 1, 4, 2)
(3, 4, 1, 2)
(3, 4, 2, 1)
(4, 1, 2, 3)
(4, 3, 1, 2)
(4, 3, 2, 1)
for {1,3,5,7} 
(3, 1, 7, 5)
(3, 5, 7, 1)
(3, 7, 1, 5)
(5, 1, 7, 3)
(5, 7, 1, 3)
(5, 7, 3, 1)
(7, 1, 3, 5)
(7, 5, 1, 3)
(7, 5, 3, 1)
for {1, 2, 2, 1} 
{(1, 2, 1, 2), (1, 1, 2, 2), (2, 1, 1, 2), (2, 2, 1, 1), (2, 1, 2, 1), (1, 2, 2, 1)}
[1 2 2 1]
(2, 1, 1, 2)
[1 2 2 1]
(2, 1, 1, 2)
[1 2 2 1]
(2, 1, 1, 2)
[1 2 2 1]
(2, 1, 1, 2)


### 1.5 Задача
Виведіть всі можливі перестановки, в яких перші $4$ елементи зростають, а наступні спадають, та порахуйте їх кількість від таких множин:
- {1, 2, 3, 4, 5, 6, 7, 8}
- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

**Зауваження.** Нехай перестановка
$\pi = \left( \sigma_1, \sigma_2, \sigma_3, \sigma_4, \sigma_5, \sigma_6, \sigma_7, \sigma_8 \right)$.
Тоді має виконуватися така умова:
$$
  \sigma_1 < \sigma_2 < \sigma_3 < \sigma_4 > \sigma_5 > \sigma_6 > \sigma_7 > \sigma_8.
$$

In [9]:
# Місце для Вашого коду
A = np.arange(1,9)

for i in permutations(A):
    if(i[0]<i[1]<i[2]<i[3]>i[4]>i[5]>i[6]>i[7]):
        print(i)
        
A = np.arange(1,11)

for i in permutations(A):
    if(i[0]<i[1]<i[2]<i[3]>i[4]>i[5]>i[6]>i[7]>i[8]>i[9]):
        print(i)


(1, 2, 3, 8, 7, 6, 5, 4)
(1, 2, 4, 8, 7, 6, 5, 3)
(1, 2, 5, 8, 7, 6, 4, 3)
(1, 2, 6, 8, 7, 5, 4, 3)
(1, 2, 7, 8, 6, 5, 4, 3)
(1, 3, 4, 8, 7, 6, 5, 2)
(1, 3, 5, 8, 7, 6, 4, 2)
(1, 3, 6, 8, 7, 5, 4, 2)
(1, 3, 7, 8, 6, 5, 4, 2)
(1, 4, 5, 8, 7, 6, 3, 2)
(1, 4, 6, 8, 7, 5, 3, 2)
(1, 4, 7, 8, 6, 5, 3, 2)
(1, 5, 6, 8, 7, 4, 3, 2)
(1, 5, 7, 8, 6, 4, 3, 2)
(1, 6, 7, 8, 5, 4, 3, 2)
(2, 3, 4, 8, 7, 6, 5, 1)
(2, 3, 5, 8, 7, 6, 4, 1)
(2, 3, 6, 8, 7, 5, 4, 1)
(2, 3, 7, 8, 6, 5, 4, 1)
(2, 4, 5, 8, 7, 6, 3, 1)
(2, 4, 6, 8, 7, 5, 3, 1)
(2, 4, 7, 8, 6, 5, 3, 1)
(2, 5, 6, 8, 7, 4, 3, 1)
(2, 5, 7, 8, 6, 4, 3, 1)
(2, 6, 7, 8, 5, 4, 3, 1)
(3, 4, 5, 8, 7, 6, 2, 1)
(3, 4, 6, 8, 7, 5, 2, 1)
(3, 4, 7, 8, 6, 5, 2, 1)
(3, 5, 6, 8, 7, 4, 2, 1)
(3, 5, 7, 8, 6, 4, 2, 1)
(3, 6, 7, 8, 5, 4, 2, 1)
(4, 5, 6, 8, 7, 3, 2, 1)
(4, 5, 7, 8, 6, 3, 2, 1)
(4, 6, 7, 8, 5, 3, 2, 1)
(5, 6, 7, 8, 4, 3, 2, 1)
(1, 2, 3, 10, 9, 8, 7, 6, 5, 4)
(1, 2, 4, 10, 9, 8, 7, 6, 5, 3)
(1, 2, 5, 10, 9, 8, 7, 6, 4, 3)
(1, 2, 6, 10, 9, 8, 7, 5, 4, 

## 2 Часткові перестановки

### 2.1 Використовуючи бібліотеку `itertools`

In [10]:
A = {1, 2, 3}
k = 2

In [11]:
# перестановки довжини k множини A
permute_k = list(permutations(A, k))
print("Перестановки довжини {} множини {}: {}".format(k,A,permute_k))
print("Кількість таких перестановок: {}".format(len(permute_k)))

Перестановки довжини 2 множини {1, 2, 3}: [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]
Кількість таких перестановок: 6


### 2.2 Задача
Нехай $n$ - розмір множини, $k$ - розмір перестановок.
Виведіть всі можливі часткові перестановки та порахуйте їх кількість для таких параметрів:
- $n = 4, k = 2$
- $n = 4, k = 3$
- $n = 5, k = 2$

Порахуйте кількість часткових перестановок для таких параметрів:
- $n = 6, k = 2$
- $n = 6, k = 4$
- $n = 8, k = 4$

In [12]:
# Місце для Вашого коду
A = np.arange(1,5)
k = 2
permute_k = list(permutations(A, k))
print("Перестановки довжини {} множини {}: {}".format(k,A,permute_k))
print("Кількість таких перестановок: {}".format(len(permute_k)))

A = np.arange(1,5)
k = 3
permute_k = list(permutations(A, k))
print("Перестановки довжини {} множини {}: {}".format(k,A,permute_k))
print("Кількість таких перестановок: {}".format(len(permute_k)))

A = np.arange(1,6)
k = 2
permute_k = list(permutations(A, k))
print("Перестановки довжини {} множини {}: {}".format(k,A,permute_k))
print("Кількість таких перестановок: {}".format(len(permute_k)))

A = np.arange(1,7)
k = 2
permute_k = list(permutations(A, k))
print("Кількість таких перестановок: {}".format(len(permute_k)))

A = np.arange(1,7)
k = 4
permute_k = list(permutations(A, k))
print("Кількість таких перестановок: {}".format(len(permute_k)))

A = np.arange(1,9)
k = 4
permute_k = list(permutations(A, k))
print("Кількість таких перестановок: {}".format(len(permute_k)))

Перестановки довжини 2 множини [1 2 3 4]: [(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4), (3, 1), (3, 2), (3, 4), (4, 1), (4, 2), (4, 3)]
Кількість таких перестановок: 12
Перестановки довжини 3 множини [1 2 3 4]: [(1, 2, 3), (1, 2, 4), (1, 3, 2), (1, 3, 4), (1, 4, 2), (1, 4, 3), (2, 1, 3), (2, 1, 4), (2, 3, 1), (2, 3, 4), (2, 4, 1), (2, 4, 3), (3, 1, 2), (3, 1, 4), (3, 2, 1), (3, 2, 4), (3, 4, 1), (3, 4, 2), (4, 1, 2), (4, 1, 3), (4, 2, 1), (4, 2, 3), (4, 3, 1), (4, 3, 2)]
Кількість таких перестановок: 24
Перестановки довжини 2 множини [1 2 3 4 5]: [(1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 3), (2, 4), (2, 5), (3, 1), (3, 2), (3, 4), (3, 5), (4, 1), (4, 2), (4, 3), (4, 5), (5, 1), (5, 2), (5, 3), (5, 4)]
Кількість таких перестановок: 20
Кількість таких перестановок: 30
Кількість таких перестановок: 360
Кількість таких перестановок: 1680


## 3 Комбінації без повторень

### 3.1 Використовуючи бібліотеку `itertools`

In [13]:
from itertools import combinations
import random as rd

In [14]:
A = {1, 2, 3}
k = 2

In [15]:
# комбінації довжини k множини A
choose_k = list(combinations(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)  ))

Комбінації довжини 2 множини {1, 2, 3}: [(1, 2), (1, 3), (2, 3)]
Кількість таких комбінацій: 3


### 3.2 Задача
Нехай $n$ - розмір множини, $k$ - розмір комбінацій.
Виведіть всі можливі комбінації без повторень та порахуйте їх кількість для таких параметрів:
- $n = 4, k = 2$
- $n = 4, k = 3$
- $n = 5, k = 2$

Порахуйте кількість комбінацій без повторень для таких параметрів:
- $n = 6, k = 2$
- $n = 6, k = 4$
- $n = 8, k = 4$

In [16]:
# Місце для Вашого коду
A = np.arange(1,5)
k = 2
choose_k = list(combinations(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,5)
k = 3
choose_k = list(combinations(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,6)
k = 2
choose_k = list(combinations(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,7)
k = 2
choose_k = list(combinations(A,k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,7)
k = 4
choose_k = list(combinations(A,k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,9)
k = 4
choose_k = list(combinations(A,k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

Комбінації довжини 2 множини [1 2 3 4]: [(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
Кількість таких комбінацій: 6
Комбінації довжини 3 множини [1 2 3 4]: [(1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4)]
Кількість таких комбінацій: 4
Комбінації довжини 2 множини [1 2 3 4 5]: [(1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]
Кількість таких комбінацій: 10
Кількість таких комбінацій: 15
Кількість таких комбінацій: 15
Кількість таких комбінацій: 70


### 3.3 Задача
Нехай $A$ - множина з $10$ елементів, кожен з яких є цілим числом від $1$ до $20$.
Тобто $$A = \{ a_i \}_{i = 1}^{10},\\ 1 \leq a_i \leq 20, \quad i = 1, \ldots, 10.$$
Скільки елементів може бути в множині, яка складається із попарних сум елементів множини $A$?
$$B = \{ b_k \, \colon \, b_k = a_i + a_j, \quad a_i, a_j \in A, \, 1 \leq i, j \leq 10, \, i \neq j \}_{k = 1}^{\textbf{?}}$$

In [17]:
# Місце для Вашого коду
A = []
B = []

for i in range(10):
    A.append(rd.randint(1,20))
print(A)

k = 2
choose_k = list(combinations(A,k))
print("Кількість елементів в множині В = {}".format(len(choose_k))) # це вже можна рахувати за відповідь, але я ще вирішив дописати 

for i in range(len(choose_k)):
    a=choose_k[i]
    B.append(a[0]+a[1])
print(B)

[4, 16, 16, 20, 8, 18, 8, 12, 2, 2]
Кількість елементів в множині В = 45
[20, 20, 24, 12, 22, 12, 16, 6, 6, 32, 36, 24, 34, 24, 28, 18, 18, 36, 24, 34, 24, 28, 18, 18, 28, 38, 28, 32, 22, 22, 26, 16, 20, 10, 10, 26, 30, 20, 20, 20, 10, 10, 14, 14, 4]


## 4 Комбінації з повтореннями

### 4.1 Використовуючи бібліотеку `itertools`

In [18]:
from itertools import combinations_with_replacement

In [19]:
A = {1, 2, 3}
k = 2

In [20]:
# комбінації довжини k множини A
choose_k = list(combinations_with_replacement(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

Комбінації довжини 2 множини {1, 2, 3}: [(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]
Кількість таких комбінацій: 6


### 4.2 Задача
Нехай $n$ - розмір множини, $k$ - розмір комбінацій.
Виведіть всі можливі комбінації з повтореннями та порахуйте їх кількість для таких параметрів:
- $n = 4, k = 2$
- $n = 4, k = 3$
- $n = 5, k = 2$

Порахуйте кількість комбінацій з повтореннями для таких параметрів:
- $n = 6, k = 2$
- $n = 6, k = 4$
- $n = 8, k = 4$

In [21]:
# Місце для Вашого коду
A = np.arange(1,5)
k = 2

choose_k = list(combinations_with_replacement(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,5)
k = 3

choose_k = list(combinations_with_replacement(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,6)
k = 2

choose_k = list(combinations_with_replacement(A,k))
print("Комбінації довжини {} множини {}: {}".format(k,A,choose_k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,7)
k = 2

choose_k = list(combinations_with_replacement(A,k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,7)
k = 4

choose_k = list(combinations_with_replacement(A,k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

A = np.arange(1,9)
k = 4

choose_k = list(combinations_with_replacement(A,k))
print("Кількість таких комбінацій: {}".format(len(choose_k)))

Комбінації довжини 2 множини [1 2 3 4]: [(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]
Кількість таких комбінацій: 10
Комбінації довжини 3 множини [1 2 3 4]: [(1, 1, 1), (1, 1, 2), (1, 1, 3), (1, 1, 4), (1, 2, 2), (1, 2, 3), (1, 2, 4), (1, 3, 3), (1, 3, 4), (1, 4, 4), (2, 2, 2), (2, 2, 3), (2, 2, 4), (2, 3, 3), (2, 3, 4), (2, 4, 4), (3, 3, 3), (3, 3, 4), (3, 4, 4), (4, 4, 4)]
Кількість таких комбінацій: 20
Комбінації довжини 2 множини [1 2 3 4 5]: [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 2), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5), (4, 4), (4, 5), (5, 5)]
Кількість таких комбінацій: 15
Кількість таких комбінацій: 21
Кількість таких комбінацій: 126
Кількість таких комбінацій: 330


### 4.3 Задача
Скільки існує 6-цифрових наборів таких, що сума перших трьох цифр дорівнює сумі останніх трьох?

**Зауваження 1.** В задачі фігурують 6-цифрові набори, а не числа. Тобто перша цифра може дорівнювати $0$.

**Зауваження 2.** Задача передбачає використання функції
[product](https://docs.python.org/3/library/itertools.html#itertools.product).

In [22]:
# Місце для Вашого коду
from itertools import product as pr

n = 0

for i in pr(range(0,10), repeat = 6):
    if (i[0] + i[1] + i[2]) == (i[3] + i[4] + i[5]):
        n+=1
print(n)

55252


### NSS
**AS_SA**

qp_db

### 4.4 Задача
Скільки існує 6-цифрових чисел, в яких дві однакові цифри не стоять поряд?

**Зауваження 1.** В задачі фігурують 6-цифрові числа, тобто перша цифра не може дорівнювати $0$.

**Зауваження 2.** Задача передбачає використання функції
[product](https://docs.python.org/3/library/itertools.html#itertools.product).

In [23]:
# Місце для Вашого коду
a = pr("0123456789","0123456789", repeat = 3)
n = 0
for i in a:
    if i[0]!= '0' and i[0]!=i[1] and i[1]!=i[2] and i[2]!=i[3] and i[3]!=i[4] and i[4]!=i[5]:
        n+=1
print(n) 


531441


In [24]:
a = pr(range(0,10), repeat = 6)
n = 0
for i in a:
    if i[0]!= '0' and i[0]!=i[1] and i[1]!=i[2] and i[2]!=i[3] and i[3]!=i[4] and i[4]!=i[5]:
        n+=1
print(n)  #Чому тут різні відповіді? 

590490
