# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['top' 'top' 'top' '4.5' '4.5' '4.5' 'top' 'top' 'top' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [3]:
# Місце для Вашого коду

a = [1,2,3,4,5,6,7,8,9,0]
size = 1
probs = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))



[8]


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [4]:
# Місце для Вашого коду
a = [1,2,3,4,5,6,7,8,9,0]
size = 24
probs = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs).reshape(4,6))



[[2 8 4 7 2 2]
 [7 6 7 5 3 0]
 [0 1 2 7 0 2]
 [3 3 0 6 9 3]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[4 4 1 0 1 2 4 1 1 2]


Згенеруйте одну випадкову цифру.

In [6]:
# Місце для Вашого коду

print(np.random.randint(low = 1, high = 100, size = 1))


[84]


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [7]:
# Місце для Вашого коду

print(np.random.randint(low = 10, high = 99, size = 20).reshape(4,5))


[[87 45 87 86 83]
 [21 37 14 70 56]
 [67 43 94 58 62]
 [63 35 27 74 61]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.8909364076321202


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [9]:
# Місце для Вашого коду

print(np.random.sample(size=12).reshape(3,4))

[[0.82713747 0.78143776 0.4256704  0.70618864]
 [0.10733646 0.25767248 0.44139476 0.14258432]
 [0.64715376 0.22082672 0.39563928 0.87965262]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [11]:
# Місце для Вашого коду
a = 3
b = 5
print( (b-a) * np.random.sample(size = 10) + a )

[3.55815221 3.9854272  3.93829764 3.51036587 3.30390558 4.75089463
 3.45625061 4.10381316 3.70041074 4.67288061]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[4 0 8 9 5 6 3 1 7 2]


Перетасуйте матрицю $M$.

In [13]:

M = np.arange(20).reshape((4, 5))
print(M)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
# Місце для Вашого коду

M = np.arange(20).reshape((4, 5))
N = M.flatten()
np.random.shuffle(N)
print(N.reshape((4,5)))


[[14 17  5  2 13]
 [11  0 19 16 10]
 [ 9  6 12 15 18]
 [ 8  7  3  4  1]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [20]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [21]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [22]:
# Місце для Вашого коду

p=0.5
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)

heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

50 heads and 50 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [23]:
# Місце для Вашого коду

tosses = np.random.randint(0, 2, size = 100)
heads = list(tosses).count(0)
tails = list(tosses).count(1)
print("{} heads and {} tails".format(heads,tails))

51 heads and 49 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [24]:
# Місце для Вашого коду

heads = 0
tails = 0

tosses = np.random.sample((1,100)) > 0.5
for i in range(len(tosses[0])):
    if tosses[0][i] == True:
        heads += 1
    else:
        tails += 1

print("{} heads and {} tails".format(heads,tails))

59 heads and 41 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [25]:
# Місце для Вашого коду

parametrs = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for i in parametrs:
    
    count_h = 0
    count_t = 0
    
    tosses = np.random.randint(2, size=i)
    for num in range(len(tosses)):
        if tosses[num] == 1:
            count_h += 1
        else:
            count_t += 1
    
    p_heads = count_h / i
    p_tails = count_t / i
    
    P_heads = sum(tosses == 1) / i
    P_tails = sum(tosses == 0) / i
    
    print('n = {}  :  P(h) = {},  P(t) = {}'.format(i, P_heads, P_tails))
    print('n = {}  :  P(h) = {},  P(t) = {}'.format(i, p_heads, p_tails))
    print("---------------------------------------------")


n = 10  :  P(h) = 0.5,  P(t) = 0.5
n = 10  :  P(h) = 0.5,  P(t) = 0.5
---------------------------------------------
n = 50  :  P(h) = 0.6,  P(t) = 0.4
n = 50  :  P(h) = 0.6,  P(t) = 0.4
---------------------------------------------
n = 100  :  P(h) = 0.54,  P(t) = 0.46
n = 100  :  P(h) = 0.54,  P(t) = 0.46
---------------------------------------------
n = 250  :  P(h) = 0.452,  P(t) = 0.548
n = 250  :  P(h) = 0.452,  P(t) = 0.548
---------------------------------------------
n = 500  :  P(h) = 0.492,  P(t) = 0.508
n = 500  :  P(h) = 0.492,  P(t) = 0.508
---------------------------------------------
n = 1000  :  P(h) = 0.473,  P(t) = 0.527
n = 1000  :  P(h) = 0.473,  P(t) = 0.527
---------------------------------------------
n = 2500  :  P(h) = 0.5084,  P(t) = 0.4916
n = 2500  :  P(h) = 0.5084,  P(t) = 0.4916
---------------------------------------------
n = 5000  :  P(h) = 0.497,  P(t) = 0.503
n = 5000  :  P(h) = 0.497,  P(t) = 0.503
---------------------------------------------
n = 10

## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [26]:
# Місце для Вашого коду

a = [1,2,3,4,5,6]
size = 60
probs = [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
K_num = np.random.choice(a, size=size, p=probs)
st_1 = sum(K_num == 1)
st_2 = sum(K_num == 2)
st_3 = sum(K_num == 3)
st_4 = sum(K_num == 4)
st_5 = sum(K_num == 5)
st_6 = sum(K_num == 6)

print("1: {} \n2: {} \n3: {} \n4: {} \n5: {} \n6: {}".format(st_1,st_2,st_3,st_4,st_5,st_6))

1: 10 
2: 12 
3: 7 
4: 8 
5: 7 
6: 16


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [27]:
# Місце для Вашого коду

import collections

parametrs = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for i in parametrs:
    
    KyB = np.random.randint(1, 7, size=i)
    KyB_num = collections.Counter(KyB)
    KyB_num = sorted(KyB_num.items())
    
    for j in range(len(KyB_num)):
        empirical_p = KyB_num[j][1] / i
        print("{}: {}".format(KyB_num[j][0], empirical_p))
    print("__________")


1: 0.2
2: 0.1
3: 0.1
4: 0.1
5: 0.2
6: 0.3
__________
1: 0.06
2: 0.14
3: 0.2
4: 0.2
5: 0.24
6: 0.16
__________
1: 0.22
2: 0.15
3: 0.12
4: 0.21
5: 0.08
6: 0.22
__________
1: 0.164
2: 0.16
3: 0.172
4: 0.18
5: 0.192
6: 0.132
__________
1: 0.17
2: 0.156
3: 0.152
4: 0.18
5: 0.136
6: 0.206
__________
1: 0.154
2: 0.185
3: 0.164
4: 0.159
5: 0.169
6: 0.169
__________
1: 0.1692
2: 0.168
3: 0.1572
4: 0.1716
5: 0.1688
6: 0.1652
__________
1: 0.1726
2: 0.1768
3: 0.1612
4: 0.1586
5: 0.1618
6: 0.169
__________
1: 0.1631
2: 0.1606
3: 0.1628
4: 0.1736
5: 0.1771
6: 0.1628
__________


## 5 Колода карт
### 5.1 Реалізація

In [28]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('7', '♢'), ('7', '♡'), ('7', '♣'), ('7', '♠'), ('Q', '♢'), ('Q', '♡'), ('Q', '♣'), ('Q', '♠'), ('1', '♢'), ('1', '♡'), ('1', '♣'), ('1', '♠'), ('2', '♢'), ('2', '♡'), ('2', '♣'), ('2', '♠'), ('J', '♢'), ('J', '♡'), ('J', '♣'), ('J', '♠'), ('9', '♢'), ('9', '♡'), ('9', '♣'), ('9', '♠'), ('K', '♢'), ('K', '♡'), ('K', '♣'), ('K', '♠'), ('8', '♢'), ('8', '♡'), ('8', '♣'), ('8', '♠'), ('6', '♢'), ('6', '♡'), ('6', '♣'), ('6', '♠'), ('3', '♢'), ('3', '♡'), ('3', '♣'), ('3', '♠'), ('10', '♢'), ('10', '♡'), ('10', '♣'), ('10', '♠'), ('4', '♢'), ('4', '♡'), ('4', '♣'), ('4', '♠'), ('5', '♢'), ('5', '♡'), ('5', '♣'), ('5', '♠')]


In [29]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

7♢, 7♡, 7♣, 7♠, Q♢, Q♡, Q♣, Q♠, 1♢, 1♡, 1♣, 1♠, 2♢, 2♡, 2♣, 2♠, J♢, J♡, J♣, J♠, 9♢, 9♡, 9♣, 9♠, K♢, K♡, K♣, K♠, 8♢, 8♡, 8♣, 8♠, 6♢, 6♡, 6♣, 6♠, 3♢, 3♡, 3♣, 3♠, 10♢, 10♡, 10♣, 10♠, 4♢, 4♡, 4♣, 4♠, 5♢, 5♡, 5♣, 5♠


In [30]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♢7, ♢Q, ♢1, ♢2, ♢J, ♢9, ♢K, ♢8, ♢6, ♢3, ♢10, ♢4, ♢5
♡7, ♡Q, ♡1, ♡2, ♡J, ♡9, ♡K, ♡8, ♡6, ♡3, ♡10, ♡4, ♡5
♣7, ♣Q, ♣1, ♣2, ♣J, ♣9, ♣K, ♣8, ♣6, ♣3, ♣10, ♣4, ♣5
♠7, ♠Q, ♠1, ♠2, ♠J, ♠9, ♠K, ♠8, ♠6, ♠3, ♠10, ♠4, ♠5


In [31]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('3', '♡'), ('8', '♠'), ('5', '♡'), ('7', '♡'), ('1', '♣'), ('7', '♣'), ('7', '♠'), ('6', '♢'), ('K', '♢'), ('10', '♡'), ('J', '♢'), ('4', '♢'), ('6', '♡'), ('8', '♢'), ('9', '♣'), ('Q', '♢'), ('7', '♢'), ('9', '♡'), ('Q', '♣'), ('6', '♠'), ('9', '♢'), ('Q', '♡'), ('2', '♡'), ('1', '♠'), ('3', '♢'), ('4', '♣'), ('3', '♣'), ('K', '♣'), ('5', '♣'), ('5', '♢'), ('8', '♡'), ('2', '♢'), ('4', '♠'), ('5', '♠'), ('4', '♡'), ('1', '♢'), ('6', '♣'), ('J', '♠'), ('K', '♠'), ('10', '♢'), ('10', '♠'), ('8', '♣'), ('10', '♣'), ('2', '♠'), ('9', '♠'), ('1', '♡'), ('J', '♣'), ('2', '♣'), ('3', '♠'), ('K', '♡'), ('Q', '♠'), ('J', '♡')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [62]:
# Місце для Вашого коду

parametrs = [10,50,100,250,500,1000,2500,5000,10000]
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠️', '♣️', '♡'}

Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
np.random.shuffle(Cards)

for j in parametrs:
    count=0
    for i in range(j):
        rand_card = np.random.randint(0,52) 
        if Cards[rand_card][0] in ['2','4','6', '8', '10']:
            count += 1
    print ("P = {} in {} attempts".format(count/j,j))

P = 0.4 in 10 attempts
P = 0.34 in 50 attempts
P = 0.44 in 100 attempts
P = 0.432 in 250 attempts
P = 0.424 in 500 attempts
P = 0.369 in 1000 attempts
P = 0.4016 in 2500 attempts
P = 0.3862 in 5000 attempts
P = 0.3838 in 10000 attempts


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [89]:
# Місце для Вашого коду

Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♣️', '♠️', '♢', '♡'}
Cards = [[Rank, Suit] for Rank in Ranks for Suit in Suits]
np.random.shuffle(Cards)

Hand1 = []
Hand2 = []
Hand3 = []
Hand4 = []
club = []
shade = []
diamond = []
heart = []

for suits in range(len(Cards)):
    if Cards[suits][1]=='♣️':
        club.append(suits)
    if Cards[suits][1]=='♠️':
        shade.append(suits)
    if Cards[suits][1]=='♢':
        diamond.append(suits)
    if Cards[suits][1]=='♡':
        heart.append(suits)

np.random.shuffle(club) 
np.random.shuffle(shade) 
np.random.shuffle(diamond)
np.random.shuffle(heart) 

"""!!!DOUBLE RANDOM SHUFFLE!!!""" 
        
for m in range(len(Cards)//4):
    if m < 4:
        Hand1.append(Cards[club[m]])
        Hand2.append(Cards[shade[m]])
        Hand3.append(Cards[diamond[m]])
        Hand4.append(Cards[heart[m]])
    if m > 3 and m < 7:
        Hand1.append(Cards[heart[m]])
        Hand2.append(Cards[club[m]])
        Hand3.append(Cards[shade[m]])
        Hand4.append(Cards[diamond[m]])
    if m >6 and m < 10:
        Hand1.append(Cards[diamond[m]])
        Hand2.append(Cards[heart[m]])
        Hand3.append(Cards[club[m]])
        Hand4.append(Cards[shade[m]])
    if m > 9:
        Hand1.append(Cards[shade[m]])
        Hand2.append(Cards[diamond[m]])
        Hand3.append(Cards[heart[m]])
        Hand4.append(Cards[club[m]])

print ('Hand1 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand1]))
print ('Hand2 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand2]))
print ('Hand3 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand3]))
print ('Hand4 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand4]))

Hand1 cards: Q♣️, 6♣️, 4♣️, 5♣️, 2♡, J♡, Q♡, Q♢, 3♢, K♢, 10♠️, K♠️, J♠️
Hand2 cards: 9♠️, 8♠️, 5♠️, 4♠️, 9♣️, 10♣️, 8♣️, K♡, 6♡, 1♡, J♢, 10♢, 5♢
Hand3 cards: 1♢, 4♢, 7♢, 6♢, 6♠️, 3♠️, 7♠️, 1♣️, 7♣️, 2♣️, 9♡, 4♡, 10♡
Hand4 cards: 5♡, 8♡, 7♡, 3♡, 2♢, 9♢, 8♢, 1♠️, 2♠️, Q♠️, 3♣️, J♣️, K♣️


### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [99]:
# Місце для Вашого коду

Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♣️', '♠️', '♢', '♡'}
Cards = [[Rank, Suit] for Rank in Ranks for Suit in Suits]
np.random.shuffle(Cards)

Hand1=[]
Hand2=[]
Hand3=[]
Hand4=[]

arr=[0 for w in range(0,16)]

for i in range (len(Cards)):
    if Cards[i][1]=='♣️' and arr[0]<5:
        arr[0]+=1
        Hand1.append(Cards[i])
        continue
    if Cards[i][1]=='♠️' and arr[1]<5:
        arr[1]+=1
        Hand2.append(Cards[i])
        continue
    if Cards[i][1]=='♢' and arr[2]<5:
        arr[2]+=1
        Hand3.append(Cards[i])
        continue
    if Cards[i][1]=='♡' and arr[3]<5:
        arr[3]+=1
        Hand4.append(Cards[i])
        continue
    if Cards[i][1]=='♡' and arr[4]<2:
        arr[4]+=1
        Hand1.append(Cards[i])
        continue
    if Cards[i][1]=='♣️' and arr[5]<2:
        arr[5]+=1
        Hand2.append(Cards[i])
        continue
    if Cards[i][1]=='♠️' and arr[6]<2:
        arr[6]+=1
        Hand3.append(Cards[i])
        continue
    if Cards[i][1]=='♢' and arr[7]<2:
        arr[7]+=1
        Hand4.append(Cards[i])
        continue
    if Cards[i][1]=='♢' and arr[8]<2:
        arr[8]+=1
        Hand1.append(Cards[i])
        continue
    if Cards[i][1]=='♡' and arr[9]<2:
        arr[9]+=1
        Hand2.append(Cards[i])
        continue
    if Cards[i][1]=='♣️' and arr[10]<2:
        arr[10]+=1
        Hand3.append(Cards[i])
        continue
    if Cards[i][1]=='♠️' and arr[11]<2:
        arr[11]+=1
        Hand4.append(Cards[i])
        continue
    if Cards[i][1]=='♠️' and arr[12]<4:
        arr[12]+=1
        Hand1.append(Cards[i])
        continue
    if Cards[i][1]=='♢' and arr[13]<4:
        arr[13]+=1
        Hand2.append(Cards[i])
        continue
    if Cards[i][1]=='♡' and arr[14]<4:
        arr[14]+=1
        Hand3.append(Cards[i])
        continue
    if Cards[i][1]=='♣️' and arr[15]<4:
        arr[15]+=1
        Hand4.append(Cards[i])
        continue

print ('Hand1 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand1]))
print ('Hand2 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand2]))
print ('Hand3 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand3]))
print ('Hand4 cards:', ", ".join([(hand[0] + hand[1]) for hand in Hand4]))

Hand1 cards: 9♣️, K♣️, 3♣️, Q♣️, 10♣️, 7♡, 3♡, 6♠️, 8♠️, 3♢, 5♢, 3♠️, K♠️
Hand2 cards: 7♠️, J♠️, 4♠️, 5♠️, Q♠️, 8♣️, 4♣️, 6♡, 4♡, 8♢, K♢, 10♢, 7♢
Hand3 cards: 6♢, 9♢, 2♢, 1♠️, 4♢, 2♠️, Q♢, 2♣️, 6♣️, 10♡, J♡, 1♡, 2♡
Hand4 cards: K♡, 8♡, 9♡, 5♡, Q♡, 9♠️, 10♠️, 1♢, 7♣️, J♢, 5♣️, J♣️, 1♣️
